language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t dthunn/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dthunn/react-test npm test

after_success:
  - docker build -t dthunn/multi-client ./client
  - docker build -t dthunn/multi-nginx ./nginx
  - docker build -t dthunn/multi-server ./server
  - docker build -t dthunn/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push dthunn/multi-client
  - docker push dthunn/multi-nginx
  - docker push dthunn/multi-server
  - docker push dthunn/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-west-3
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-west-2-466578905758
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
